rainforestapp/rainforest-cli

- lib/rainforest/cli.rb
- lib/rainforest/cli/options.rb
Changed the default response to displaying the help if no options are specified versus displaying the cryptic "You must pass your API token using: --token TOKEN" error, and adding an explicit --help.
> Improved usability; display help by default

- CHANGELOG.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/csv_importer.rb
- lib/rainforest/cli/http_client.rb
- lib/rainforest/cli/runner.rb
- rainforest-cli.gemspec
- spec/http_client_spec.rb
fixes #58 
Also fixes some more dependency warnings when building gem.
```
$ gem build rainforest-cli.gemspec
WARNING:  description and summary are identical
WARNING:  pessimistic dependency on parallel (~> 1.6.1) may be overly strict
if parallel is semantically versioned, use:
add_runtime_dependency 'parallel', '~> 1.6', '>= 1.6.1'
WARNING:  pessimistic dependency on ruby-progressbar (~> 1.7.5) may be overly strict
if ruby-progressbar is semantically versioned, use:
add_runtime_dependency 'ruby-progressbar', '~> 1.7', '>= 1.7.5'
WARNING:  pessimistic dependency on rainforest (~> 2.1.0) may be overly strict
if rainforest is semantically versioned, use:
add_runtime_dependency 'rainforest', '~> 2.1', '>= 2.1.0'
WARNING:  pessimistic dependency on rake (~> 10.4.2, development) may be overly …
```
> Retrying on Timeouts and HTTP errors

- CHANGELOG.md
- lib/rainforest/cli/uploader.rb
- spec/rainforest-example/example_test.rfml
- spec/uploader_spec.rb
fixes #61
Do not merge until backend change is shipped first.
Edit: backend shipped.
> Remove 'ro' tag in favor of source 'rainforest-cli'

- Gemfile
- circle.yml
It appears to be breaking PRs from people without write access. GitHub does not
have any way to have comment-only permission so Rainforest bot cannot post
comments in PRs.
> Remove Circlemator

- README.md
- lib/rainforest/cli/options.rb
- spec/cli_spec.rb
Rainforest token, if not given with `--token`, is fetched from the `RAINFOREST_API_TOKEN` environment variable.
> get token from environment variable

- lib/rainforest/cli/uploader.rb
- spec/uploader_spec.rb
The flag makes sure the test is read-only, which is important in case something fails later along in the upload process.
> Hotfix: add rainforest-cli attribute for empty tests

- lib/rainforest/cli/validator.rb
- spec/validation-examples/duplicate_rfml_ids/file1.rfml
- spec/validation-examples/duplicate_rfml_ids/file2.rfml
- spec/validator_spec.rb
Addresses #80 by failing validation if there are tests with the same rfml_id.
> Adds dup rfml id validation

- lib/rainforest/cli/http_client.rb
- lib/rainforest/cli/runner.rb
- spec/cli_spec.rb
We ran into this today when running the Rainforest CLI for the first time.  I'm not a ruby developer, but attempted to add retry support into the post method via this PR.
```
/usr/share/ruby/2.3/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
from /usr/share/ruby/2.3/net/protocol.rb:136:in `readuntil'
from /usr/share/ruby/2.3/net/protocol.rb:146:in `readline'
from /usr/share/ruby/2.3/net/http/response.rb:40:in `read_status_line'
from /usr/share/ruby/2.3/net/http/response.rb:29:in `read_new'
from /usr/share/ruby/2.3/net/http.rb:1437:in `block in transport_request'
from /usr/share/ruby/2.3/net/http.rb:1434:in `catch'
from /usr/share/ruby/2.3/net/http.rb:1434:in `transport_request'
from /usr/share/ruby/2.3/net/http.rb:1407:in `request'
from …
```
> Add timeout exception handling to HttpClient::post

- lib/rainforest/cli/options.rb
- spec/options_spec.rb
fixes #118 
The API allows any browser to pass at the moment but it will create an empty run... will add another PR to return an error if the browser is invalid.
> Remove browser exception and allow the API to validate instead

- lib/rainforest/cli/exporter.rb
- spec/exporter_spec.rb
Fixing issue https://github.com/rainforestapp/rainforest-cli/issues/115
@rainforestapp/customer-product 
I'm not confident with the spec I wrote tho. Please somebody make sure its good enough.
> Exporting tests with --embed-tests now keeps the redirect flag

- .rvmrc
- README.md
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- spec/cli_spec.rb
- spec/options_spec.rb
Closes #98
@epaulet this would make it easier to run our unit tests in parallel
with RF tests. What do you think?
> Add option to wait for existing run

- README.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/http_client.rb
- lib/rainforest/cli/junit_outputter.rb
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/reporter.rb
- lib/rainforest/cli/runner.rb
- rainforest-cli.gemspec
- spec/fixtures/failed_test_response.json
- spec/fixtures/runs_response.json
- spec/fixtures/tests_response.json
- spec/http_client_spec.rb
- spec/junit_outputter_spec.rb
- spec/options_spec.rb
- spec/reporter_spec.rb
Add junit output for rainforest runs
-----------------------------------
Must be used in forground mode.  Uses the run id and client token to
query the rainforest api after a rainforest run has completed to build
up pass/fail information about the run.  For failed test cases uses the
"notes" given by approved testers who voted no to provide failure
reasons.
Generating a useful Junit output from the API takes at least two GETs.  A hit on `run` and a hit on `tests`, the former to get information about the total number of tests, the amount of time it was run etc, while the latter is needed to get slightly more detail for each test case efficiently. The tests endpoint allows the parser to determine the amount of time the test took to complete (typical content of Junit reports).
Where the …
> Junit output

- lib/rainforest_cli.rb
Uploads were broken as part of #178 because the API key is no longer set for the areas that still use the Ruby gem.
> Fix uploads

- lib/rainforest_cli/test_parser/step.rb
- spec/rainforest_cli/test_parser/step_spec.rb
Currently we don't check if the parameters for `file.download` and `file.screenshot` are already in place. We try to replace them all and give an error.
> Don't try to parameterize values that are already set

- lib/rainforest_cli/test_parser.rb
- spec/rainforest-example/example_test.rfml
- spec/rainforest_cli/test_parser_spec.rb
We no longer need to save test meta-data in the notes section, just regular notes.
> Don't upload test meta data to description anymore

- .travis.yml
- http_client.go
- rainforest-cli.go
- runner.go
- runner_test.go
Tests can be run in foreground. Example output:
```
Run 78949 is queued and is 0% complete
Run 78949 is validating and is 0% complete
Run 78949 is in_progress and is 0% complete
...
Run 78949 is in_progress and is 81% complete
Run 78949 is in_progress and is 81% complete
Run 78949 is in_progress and is 87% complete
...
Run 78949 is in_progress and is 100% complete
Run 78949 is now complete and has failed
The detailed results are available at https://app.rainforestqa.com/runs/78949
```
options also added.
TODO:
Specs
> [WIP] Refactor: Go runs

- .gitignore
- README.md
- rainforest-cli.go
- rainforest/rainforest.go
- rainforest/rainforest_test.go
- rainforest/reporter.go
- rainforest/reporter_test.go
- reporter.go
- reporter_test.go
- runner.go
- runner_test.go
Should be merged after #212 since this branch was based off of that.
TODO:
----------
Sample output of logs:
```
$ go build && ./rainforest-cli report 79593 --junit-file example.xml
2016/11/28 14:24:57 Creating JUnit report for run #79593: example.xml
2016/11/28 14:24:57 Fetching details for run #79593
2016/11/28 14:24:59 Fetching information for failed test #39168
2016/11/28 14:24:59 Fetching information for failed test #39176
2016/11/28 14:24:59 Fetching information for failed test #39185
2016/11/28 14:24:59 Fetching information for failed test #39178
2016/11/28 14:25:01 Fetching information for failed test #39182
2016/11/28 14:25:01 Fetching information for failed test #39181
2016/11/28 14:25:01 Fetching information for failed test #39194
2016/11/28 14:25:01 Fetching information for …
```
> [Review] JUnit Reports in Go

- circle.yml
- glide.lock
- glide.yaml
- rainforest-cli.go
- update.go
This adds `update` command which can be used to manually trigger updates and switch between channels and auto-updates that are ran async while cli runs.  
I've also set up 3 release channels:
- `stable` for normal stable releases, that gets pushed from tagged releases in form of `v2.1.3`
- `beta` for beta releases, gets pushed from tag on any branch in form of `v2.1.3-beta.1`
- `dev` bleeding edge channel, gets pushed after every merge to develop - used to hopefully run RF tests against it.  
All of the needed keys are set as env vars in Circle.
> [Review] Add self-updating to the client

- rainforest/tests.go
Go version fix for #244 
Since the zero value for a string is an empty string, this should work fine as the API accepts an empty string for a start URI.
> Start URI missing fix for v2

- CHANGELOG.md
- lib/rainforest_cli/test_parser.rb
- lib/rainforest_cli/version.rb
- spec/rainforest_cli/test_parser_spec.rb
- spec/validation-examples/parse_errors/no_question.rfml
- spec/validation-examples/parse_errors/no_rfml_id.rfml
- spec/validation-examples/parse_errors/no_title.rfml
Title is a required field, but we haven't been validating for it.
Example output:
```
$ bin/rainforest validate --test-folder spec/validation-examples/parse_errors/
I, [2017-03-02T09:10:02.328909 #56181]  INFO -- : Validating parsing errors...
E, [2017-03-02T09:10:02.329023 #56181] ERROR -- : Parsing errors:
E, [2017-03-02T09:10:02.329048 #56181] ERROR -- :
E, [2017-03-02T09:10:02.329068 #56181] ERROR -- : 	rainforest-cli/spec/validation-examples/parse_errors/no_question_mark.rfml
E, [2017-03-02T09:10:02.329094 #56181] ERROR -- : 	Line 5: Missing ?
E, [2017-03-02T09:10:02.329160 #56181] ERROR -- : 	rainforest-cli/spec/validation-examples/parse_errors/no_rfml_id.rfml
E, [2017-03-02T09:10:02.329232 #56181] ERROR -- : 	Field rfml_id: Missing RFML ID. Please start a line #! followed by a …
```
> Validate for test title presence

- CHANGELOG.md
- lib/rainforest_cli/exporter.rb
- lib/rainforest_cli/version.rb
- spec/rainforest_cli/exporter_spec.rb
Self explanatory. The export command does not parse the test's site id.
> Parse site id on export (v1)

- rfml.go
- rfml_test.go
Replace characters that are reserved in Linux/Windows operating systems with an underscore and lowercase all test titles.
> Replace more illegal filename characters with underscore

- rainforest/rfml.go
- rainforest/rfml_test.go
- rainforest/tests.go
- rainforest/tests_test.go
If you leave
`# browsers:`
blank, you will get the following error:
"You have selected at least one unauthorized browers."
Because the CLI will send the following attribute to the server
`{ "browsers": [""] }`
This PR should fix that (and a similar issue for tags), but not omitting the `browsers` or `tag` attributes in the body of the request, and instead sends an empty array if the browser/tag list is empty or omitted.
> Empty browsers and tags attributes fix

- rainforest/rfml.go
- rainforest/rfml_test.go
This is the behavior that existed in 1.X:
https://github.com/rainforestapp/rainforest-cli/blob/version-1/lib/rainforest_cli/uploader/uploadable_parser.rb#L39
> Upload files anyway if embedded files do not exist

- CHANGELOG.md
- rainforest/tests.go
- rainforest/tests_test.go
This just ignores remote file references for already uploaded files, eg `{{ file.screenshot(1234, h4sD5k) }}` as they can be left as is for uploading.
> RF-3170 Ignore already uploaded files

- CHANGELOG.md
- README.md
- rainforest-cli.go
So that giving bad flags doesn't appear the same as having a passing
test suite
https://rainforest.atlassian.net/browse/RF-2789
No idea how to test this?
```
$ ./rainforest-cli --foo
2017/08/26 00:19:29 Unknown argument
```
> RF-2789 Return false exit status for unknown flags

- runner.go
- runner_test.go
When waiting for a run to complete, instead of failing if we get an API
error, backoff and retry upto 5 times.
> RF-2852 Backoff if the API returns an error

- CHANGELOG.md
- rainforest-cli.go
- rfml.go
- rfml_test.go
We were forgetting to wrap the errors properly in a couple of instances.
The error output has the file path in it for validations:
```
$ ./testing --skip-update validate
2017/10/06 13:44:38 spec/rainforest/0000097596_testing_the_cli.rfml: RFML parsing error in line 11: Each step must contain a question, with a `?`
```
> Add file path to validation errors

- CHANGELOG.md
- rainforest-cli_test.go
- reporter.go
- reporter_test.go
- rfml_test.go
Also did some minor refactoring since we weren't using the one of the methods attached to the reporter struct.
> Add default JUnit report name

- CHANGELOG.md
- rainforest/rainforest.go
- rainforest/reporter.go
- rainforest/reporter_test.go
- reporter.go
- reporter_test.go
Since "no" does not always mean "failed" anymore on step results, I explicitly check for failure now and put together the appropriate failure message (either from the "note" attribute which is a failure message or the "comment" attribute which is the reason the step was flagged).
> Report failures due to RF result overrides in JUnit reports

- CHANGELOG.md
- rainforest-cli.go
To prevent cases like this
```
Edwards-MacBook-Pro:rainforest-cli edward$ rainforest run --folder 123
2017/10/26 10:53:48 folder cannot be specified with run -f
Edwards-MacBook-Pro:rainforest-cli edward$ rainforest -v
rainforest version 2.8.3 - stable channel - build: e2ca7e37
```
> default -f flag value to false

- rainforest-cli.go
- rainforest-cli_test.go
Should fix this problem:
```
$ rainforest run -f foo.rfml
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0x351440, 0xc4200120e0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.shuffleFlags(0xc42000a240, 0x4, 0x4, 0x533680, 0xc420014fa0, 0xc420017380)
/home/ubuntu/.go_workspace/src/github.com/rainforestapp/rainforest-cli/rainforest-cli.go:479 +0x7dc
main.main()
/home/ubuntu/.go_workspace/src/github.com/rainforestapp/rainforest-cli/rainforest-cli.go:452 +0x243e
```
> Fix index out of bounds when -f flag is the final flag in a command

- runner.go
Allows a case when an empty argument is converted to `"0"`.
Without this after casting `feature` to `0` resulted in `feature cannot be specified with run -f`.
> [bugfix] allow 0 as a string

- rainforest/tabularvars.go
- rainforest/tabularvars_test.go
The API now returns `null` sometimes for `created_at` which causes some issues with parsing time in go 1.7.3. We don't use this field anyway so just removing it for a quick fix.
> RF-4314 remove unused generator fields to patch a time parsing issue

- rainforest/tabularvars.go
- rainforest/tabularvars_test.go
The API issue has been addressed so this temporary fix can be reverted.
> Revert "RF-4314 remove unused generator fields to patch a time parsing issue"

- rfml.go
- rfml_test.go
> [RF-6316] return a cli.ExitError if rm command fails

- rainforest-cli.go
The CLI messages show up correctly this way.
Before
```bash
$ go build -o testing *.go && ./testing --skip-update --version
testing version 2.10.2
```
After
```bash
$ go build -o testing *.go && ./testing --skip-update --version
Rainforest CLI version 2.10.2
```
> Update app name

- CHANGELOG.md
- rainforest-cli.go
- rainforest/rfml.go
- rainforest/rfml_test.go
The API validates the state parameter already so the local validation is unnecessary.
> RF-10851 remove local test state validation

- README.md
- rainforest-cli.go
- runner.go
- runner_test.go
Supports executing tests with RF automation via `--crowd automation` option to replicate select options from the UI.
The cli prints the known error If requested tests are missing screenshots or contain english steps
```
2019/07/19 12:30:32 RF API Error (400): Requested automation, but tests [2] are not automated
```
> RF-14712 automation crowd flag

- README.md
Give a link to the API documentation so technical users can discover our
API.
Also update a bunch of the verbage which is overly verbose for my
tastes.
See the new version at https://github.com/rainforestapp/rainforest-cli/blob/a48d14a8576f81752fe2962a9756d8a1ed7f7d23/README.md
> Update README with link to API documentation

- README.md
- rainforest-cli.go
- rainforest-cli_test.go
- rainforest/runner.go
- rainforest/runner_test.go
- reporter.go
- reporter_test.go
- runner.go
- runner_test.go
We've had the endpoint for ages, but a wrapper for it was never added to the CLI (until now 🎉). The implementation and tests are heavily inspired by the "create a run from a run group" flow.
```bash
> ./rainforest-cli rerun 622054 --debug
Trying https://app.rainforestqa.com/api/1/runs/622054/rerun_failed...connected
POST HTTP/1.1
User Agent: rainforest-cli/2.15.3 [rainforest golang lib/2.0.0]
Host: app.rainforestqa.com
2020/07/03 21:59:32 Run 622146 has been created.
```
=> https://app.rainforestqa.com/runs/622146
This also adds `id` attributes to the `testsuite` and `testcase` nodes of the JUnit file, to make it real easy to get the created run ID when using the `--junit-file` option:
```bash
> ./rainforest-cli rerun 622054 --junit-file results.xml
...
> xmllint --xpath …
```
> [RF-18165] Add rerun command

- .circleci/config.yml
The docs call `equinox publish` [with the `--version` flag](https://equinox.io/docs#promote-release), but the release tool itself seems to expect a `--release` flag instead:
```
~$ equinox publish --help
NAME:
equinox publish - publish a release to a channel
USAGE:
equinox publish [command options] [arguments...]
OPTIONS:
--app value         publish release for this equinox app
--channel value     publish release to this channel
--config value      path to configuration file
--release value     release to publish
--token value       equinox.io credential token
--log value         path to log file, 'stdout', 'stderr' or 'false' (default: "false")
--log-level value   logging level (default: "info")
--log-format value  log record format: 'term', 'logfmt', 'json' (default: "term")
```
Which …
> [RF-4338] Properly call equinox publish when releasing stable or beta versions

- rainforest-cli.go
The `POST /runs` endpoint defaults to `default` if no `crowd` param is passed in, so this PR will not result in any change in behavior for runs created via that endpoint.
The `POST /run_groups/:id/runs` endpoint defaults to the run group's `crowd` setting, so the only change will be for anyone creating runs for a run group with a non-`default` `crowd` setting while not passing in a `--crowd` flag. Those runs are currently created with the `default` crowd, and will now be whatever the run group's `crowd` setting is.
> Remove default value for --crowd flag

- rainforest/rfml.go
- rainforest/rfml_test.go
I've cherry-picked commits from Forked PR https://github.com/rainforestapp/rainforest-cli/pull/390 created by @mikesbrown
because CircleCI does not run on Forked PRs for Security reasons.
---
Fixes #389
This seemed straightforward enough that I could submit a PR to fix, should you desire it. I've written a few tests to ensure desired behavior. Note that this should:
Preserve behavior in which enabled state is not explicitly written with rainforest download
Preserve behavior in which rainforest new does not write out any state
Write out any new state added to the system in the future
> RF-19424 Preserve draft state

- .circleci/config.yml
Docker are changing their TOS to rate limit unauthenticated `docker pull`
from the start of November. The rate limiting is based on IP, so builds on
Circle will be immediately impacted. Use a paid-for account and contexts to
configure a user to pull down docker images for CI/CD.
> RF-19855 Use DockerHub user for pulling down images

- README.md
- rainforest-cli.go
- rainforest-cli_test.go
- reporter.go
- reporter_test.go
- runner.go
- runner_test.go
This should address #396. When retrying, the console output looks like this:
```
2020/12/17 16:26:38 Run 674699 is in_progress and is 0% complete
2020/12/17 16:26:44 Run 674699 is in_progress and is 50% complete
2020/12/17 16:26:49 Run 674699 is in_progress and is 50% complete
2020/12/17 16:26:55 Run 674699 is in_progress and is 50% complete
2020/12/17 16:27:00 Run 674699 is in_progress and is 50% complete
2020/12/17 16:27:05 Run 674699 is in_progress and is 50% complete
2020/12/17 16:27:11 Run 674699 is in_progress and is 50% complete
2020/12/17 16:27:16 Run 674699 is now complete and has failed
2020/12/17 16:27:16 Creating JUnit report for run #674699: output.xml
2020/12/17 16:27:16 Fetching details for run #674699
2020/12/17 16:27:16 Fetching information for failed test #273949 …
```
> [RF-20430] Add --max-reruns flag to the run command

- runner.go
Use `os.Executable()` (golang >=1.8) to get the path to the RF CLI when
re-execing it for reruns. This can fail if the file is moved, but it
doesn't seem to be possible to exec based on a FD reliably, so this is
probably good enough.
> RF-20670 Locate the rainforest binary from the executable

- CHANGELOG.md
- rainforest-cli.go
Handle when the rainforest binary is not called `rainforest-cli`.
> RF-20670 Release --max-reruns fix

- README.md
- rainforest-cli.go
We don't require the site_id to be specified when setting the
custom_url. Update the documentation to reflect this.
See runner.go#L390-L415 for the code that uses custom-url to see the
lack of dependencies.
> RF-21068 Update custom-url documentation

- reporter.go
- reporter_test.go
Provide URLs to the app so it's easier to hop from the CircleCI display of failed results to the failure and diagnose what happened.
This generates junit XML that looks like:
```
<testsuite id="761688" name="Rainforest - master 188298 2021-07-20T13:50:15Z" tests="1" errors="0" failures="1" time="734.472">
<testcase id="204138" name="Embed Test" time="580">
<failure type="chrome_1440_900" message="https://app.rainforestqa.com/runs/761688/tests/204138">/failure>
</testcase>
</testsuite>
```
which is rendered by Circle like this:
You can then hightlight the URL, right-click and select "go to ..." to open the failed test in a new tab. It'd be nicer if Circle gave you an actual clickable link - but I don't know how to get that out of their renderer.
> RF-22011 report urls for failures

- .circleci/config.yml
The plan is to release this a `2.21.1`, and then we'll be able to tell anyone still using `2.20.0` and below that they need to update.
> [RF-21914] Stop publishing releases to Equinox

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Dockerfile
- rainforest-cli.go
Keeps things consistent whether you're installing from GH releases or using our Docker image.
> Use rainforest rather than rainforest-cli in Docker image as well

- .circleci/config.yml
- CHANGELOG.md
- go.mod
- go.sum
- rainforest-cli.go
- runner.go
- update.go
This is so that the CircleCI Orb and GitHub Actions can easily fetch the run ID for rerun purposes, without needing to install `libxml` to parse the JUnit each time (the workaround they're currently using).
I didn't add it to the README because I figured it's not of much use for other use cases? The flag is documented in the CLI itself.
I also updated `urfave/cli` to v1 latest since we were still on a super old SHA (not even a tag), which was annoying when reading their documentation. Upgrading to v2 involves breaking changes (most notably, it'll require users to set all flags before passing in arguments), so I opted against doing that in this PR.
> [RF-23055] Add `--save-run-id` flag to `run` and `rerun` commands

- .circleci/config.yml
The version we're currently using are deprecated and will be removed next month: https://discuss.circleci.com/t/deprecation-notice-xcode-11-0-0-11-1-0-11-2-1-11-3-1/42261
> RF-23162 Switch to latest Xcode version in CI

- CHANGELOG.md
- mobile_upload.go
- rainforest-cli.go
Rainforest now supports Android App Bundles, so we should let the cli upload them.
> RF-23329 - Update allowed extensions for mobile app uploads to include `.aab`

- CHANGELOG.md
- README.md
- rainforest-cli.go
- rainforest/rainforest.go
- rainforest/rainforest_test.go
- rainforest/resources.go
- rainforest/resources_test.go
- rainforest/rfml.go
- rainforest/rfml_test.go
- rainforest/runner_test.go
- rainforest/tests.go
- rainforest/tests_test.go
- resources.go
- resources_test.go
- runner.go
- runner_test.go
Rename certain things to match their in-app name, while maintaining support for the legacy names.
- `rainforest run --conflict abort[-all]` => `rainforest run --conflict cancel[-all]`
- `rainforest browsers` => `rainforest platforms`
- `rainforest run --browser[s] chrome,firefox` => `rainforest-run --platform[s] chrome,firefox`
- RFML: `# browsers: chrome,firefox` => `# platforms: chrome,firefox`
```
> ./build/rainforest --skip-update run --run-group 9502 --conflict abort
RF API Deprecation: abort is deprecated; use cancel instead
2022/03/16 14:53:20 Run 882659 has been created. The detailed results are available at https://app.rainforestqa.com/runs/882659
```
> [RF-22235] Update terminology

- CHANGELOG.md
- README.md
- rainforest-cli.go
- rainforest/rainforest.go
- rainforest/resources.go
- rainforest/runner.go
- rainforest/runner_test.go
- runner.go
- runner_test.go
Regardless of which flag users use, we'll send `execution_method` to the backend.
This PR also updates the output of the `run_groups` command to show the execution method rather than the crowd.
> [RF-24889] Add `--execution-method` flag, deprecate `--crowd`

- rainforest/tabularvars.go
- tabularvars.go
- tabularvars_test.go
We'll want to update the wording everywhere to match what's in the webapp ("Test Data" rather than "Tabular Variable"), but this is just a quick fix so we don't clobber an existing description when updating an existing generator.
> [RF-25598] Reuse existing description when overwriting an existing generator

- README.md
- rainforest/rfml.go
- rainforest/rfml_test.go
- rainforest/tests.go
- tests.go
- tests_test.go
Edit: I just marked this as DNM because we don't want this released until we coordinate with Domino on a time that works for them. As of this moment @pyromaniackeca has been asked to shepherd this release out when it makes sense to do so.
Adds support for downloading and uploading tests and snippets via RFML. This introduces a new RFML field `type` that can be either `test` for top-level tests or `snippet` for the new reusable snippet-type tests (formerly "embedded tests").
* Running `rainforest download` will make sure all existing tests have their `type` set correctly.
* Running `rainforest new` will generate a new RFML file with its `type` set to `test`. You can manually change that to `snippet` if you need to embed it in another test/snippet.
* Running `rainforest upload` will update …
> RF-24826 Add snippet support to RFML files

- README.md
- branches.go
- branches_test.go
- rainforest-cli.go
- rainforest/branches.go
- rainforest/branches_test.go
- rainforest/runner.go
- rainforest/runner_test.go
- rainforest/tests.go
- rainforest/tests_test.go
- runner.go
- runner_test.go
- tests.go
- tests_test.go
This PR adds the following commands to the cli:
- `branch new <name>` creates a new branch
- `branch delete <name>` deletes an existing branch
- `branch merge <name>` merges an existing branch
It also adds the `--branch <name>` option to the `run` and `upload` commands enabling them to be applied to a branch.
I've added one command per commit and a separate refactoring commit, so reviewing per commit might be easier.
> [RF-25461] Add branching support to rainforest CLI

- CHANGELOG.md
- rainforest-cli.go
- rainforest/environments.go
- rainforest/environments_test.go
- runner.go
- runner_test.go
Otherwise default to the existing behavior.
This will help clients with tons of concurrent temporary environments to distinguish between them:
> Use run description for temporary env name if one is present

- CHANGELOG.md
- README.md
- rainforest-cli.go
- rainforest/resources.go
Pagination code is copy-pasted from what we already do when fetching features and folders.
> [RF-26747] Handle paginated responses from backend when fetching sites and environments

- CHANGELOG.md
- branches.go
- branches_test.go
- rainforest/branches.go
- rainforest/resources.go
`GET /branches?name=<name>`'s behavior is changing to be a (case-insensitive, partial match) filter rather than a (exact-match) lookup. This PR updates `getBranchID` to handle that change by returning the branch with the expected name rather than blindly returning the first branch.
> [RF-26790] Update getBranchID to handle receiving multiple branches from the backend

- CHANGELOG.md
- README.md
- rainforest-cli.go
- rainforest/tabularvars.go
- rainforest/tabularvars_test.go
- tabularvars.go
- tabularvars_test.go
I missed this in #469. We fetch generators when attempting to create a new one (to know whether we should fail or overwrite, depending on whether the `--overwrite` flag is used).
Since the backend is also adding filtering by type and name to the endpoint, I added those parameters as well in order to reduce the size of the response from the backend as much as possible.
> [RF-26805] Handle paginated response from `GET /generators`

- CHANGELOG.md
- README.md
- rainforest-cli.go
- tests.go
- tests_test.go
The backend API now requires `type` to be sent when creating a test. We added test types to the CLI in 832898b12ec58947b9710bd5d6e1231040646918, but only when uploading a single test. This wasn't caught in specs because we had no tests for uploading new tests, only for updating existing tests. I've updated the tests to cover:
- uploading a single new test
- uploading a single existing test
- uploading multiple tests (both new and existing)
The cleaner fix would be to DRY up the code between uploading a single RFML file or multiple files, but for now this is hopefully good enough.
> [RF-26554] Fix uploading a batch of new tests

- CHANGELOG.md
- README.md
- rainforest-cli.go
- rainforest/tests.go
- rainforest/tests_test.go
the CLI currently calls `tests` endpoint without slimmer=true, but it seems like things should just work with the slimmed down response. 
Because the response is timing out, some clients are getting `502` errors through the CLI.
> RF-27499 adding slimmer=true for tests endpoint since tests download is timing out for some clients

- runner.go
- runner_test.go
Prior to this PR, if you passed a `custom-url` with an empty fragment e.g `https://example.com#` the `#` would be stripped off and a temporary environment with url `https://example.com` would be created instead. 
This happens because we parse the `custom-url` (see [here](https://github.com/rainforestapp/rainforest-cli/blob/d6624ff90357a64180d43e525c24650713544018/runner.go#L420)) and parsing urls like so `url.Parse(myUrl)` in golang has a [known issue](https://github.com/golang/go/issues/29603). 
The fix implemented ensures that `#` is retained in the url even if the fragment is empty.
Related issue: #473
> Allow creation of temporary environment using custom-url with empty fragment

- .circleci/config.yml
This launches direct-connect in the background, along with a simple python http server, and then kicks off a rainforest run that should connect to the python server and verify the index.html says RainforestCLI Direct Connect Test.
The account this is configured to use has a direct connect tunnel (id 6), and the run group is configured to use that tunnel.
> RF-34749 - Add integration test for Rainforest Direct Connect

- README.md
- direct_connect.go
- rainforest-cli.go
- rainforest/direct_connect.go
* Remove the `"default"` value for the `tunnel-id` argument for direct connect.
* Output the connection name to console when the tunnel is established.
* Add instruction to README to install submodules.
> RF-35226 remove default tunnel id argument value

- rainforest/files.go
- rainforest/rfml.go
- rainforest/rfml_test.go
The backend changed the way we expose files, they now need to use a specific file_key instead of the internal ID. Tested this in my staging account to verify it works properly for both newly uploaded files as well as existing matches.
> RF-37622 - Use the file_key instead of the ID for download links
