rainforestapp/rainforest-cli

- lib/rainforest/cli/csv_importer.rb
- lib/rainforest/cli/version.rb
- spec/csv_importer_spec.rb
- spec/fixtures/variables.txt
> Fix bad API_URL constant

- README.md
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- lib/rainforest/cli/version.rb
- spec/options_spec.rb
> Add run description

- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- spec/options_spec.rb
> Use description, not run-description

- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- spec/cli_spec.rb
- spec/options_spec.rb
@rainforestapp/devs I can has review plz?
> Add environment support for Max

- README.md
- spec/options_spec.rb
~~Waiting for https://github.com/rainforestapp/Rainforest/pull/6204 to be approved first.~~ (merged)
Fixes #33
> Update README for "conflict abort" change and addition of environment ids

- lib/rainforest/cli/git_trigger.rb
- spec/git_trigger_spec.rb
Fixes https://github.com/rainforestapp/rainforest-cli/issues/38
> Parse tags after `@rainforest` for git trigger

- lib/rainforest/cli/options.rb
- lib/rainforest/cli/test_files.rb
- spec/csv_importer_spec.rb
- spec/options_spec.rb
- spec/test_files_spec.rb
And some other code clean up
fixes #50
> Create all parent folders required for test folder

- .rubocop.yml
- CHANGELOG.md
- lib/rainforest/cli/version.rb
- rainforest-cli.gemspec
fixes #47 and prep for release of bug fix
> Release: 1.2.1

- .rubocop.yml
- rainforest-cli.gemspec
> Hotfix(1.2.1): ~>

- CHANGELOG.md
Release was pushed back for some extra bug fixes.
> Update release date for 1.2.1

- .gitignore
- .travis.yml
- Gemfile
- circle.yml
- lib/rainforest/cli/http_client.rb
- spec/http_client_spec.rb
- spec/spec_helper.rb
> Add support for ruby 1.9.3

- README.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/exporter.rb
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/test_files.rb
- lib/rainforest/cli/test_importer.rb
- lib/rainforest/cli/uploader.rb
- lib/rainforest/cli/validator.rb
- spec/csv_importer_spec.rb
- spec/exporter_spec.rb
- spec/spec_helper.rb
- spec/test_files_spec.rb
- spec/uploader_spec.rb
> Embedded Test Export

- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- spec/options_spec.rb
> Support for app source urls

- README.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/sites.rb
- lib/rainforest/cli/test_parser.rb
- lib/rainforest/cli/uploader.rb
- spec/rainforest-example/example_test.rfml
- spec/sites_spec.rb
- spec/uploader_spec.rb
> Add support for sites

- CHANGELOG.md
- README.md
- lib/rainforest/cli/version.rb
> Prepare new version release

- README.md
- lib/rainforest/cli/options.rb
Will need an easy way to reference folder ID next. But updating this for now.
> Update description for app-source-url

- CHANGELOG.md
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/runner.rb
- lib/rainforest/cli/version.rb
- spec/options_spec.rb
@epaulet can you review please?
> Add crowd selection support

- lib/rainforest/cli/options.rb
fixes #88 
related docs http://ruby-doc.org/stdlib-2.3.0/libdoc/optparse/rdoc/OptionParser.html#method-i-ver
> Add --version command

- README.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/resources.rb
- lib/rainforest/cli/test_parser.rb
- spec/resources_spec.rb
> Add a browser name reference

- lib/rainforest/cli/exporter.rb
- spec/exporter_spec.rb
> Remove newlines from actions and responses

- lib/rainforest/cli/runner.rb
- spec/runner_spec.rb
Fixes #101
Depends on https://github.com/rainforestapp/Rainforest/pull/8148
@rainforestapp/core @ukd1
> App uploader

- lib/rainforest/cli.rb
- lib/rainforest/cli/deleter.rb
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/test_files.rb
- lib/rainforest/cli/test_parser.rb
- spec/deleter_spec.rb
- spec/exporter_spec.rb
- spec/options_spec.rb
- spec/test_files_spec.rb
- spec/test_parser_spec.rb
- spec/uploader_spec.rb
- spec/validator_spec.rb
Addresses https://github.com/rainforestapp/rainforest-cli/issues/43
> add rm command

- README.md
- lib/rainforest/cli/test_files.rb
- spec/test_files_spec.rb
> Make new test titles customizable

- lib/rainforest/cli/options.rb
- spec/options_spec.rb
> fix bug with file name for new test being expanded

- README.md
- lib/rainforest/cli/constants.rb
- lib/rainforest/cli/exporter.rb
- lib/rainforest/cli/uploader.rb
I also reduced the default number of threads because it was overwhelming the API it seems.
> Allow adjustable thread concurrency

- lib/rainforest/cli/exporter.rb
- spec/exporter_spec.rb
> Add redirect flag for first steps after embedded tests

- README.md
- lib/rainforest/cli/exporter.rb
- lib/rainforest/cli/remote_tests.rb
- spec/exporter_spec.rb
- spec/remote_tests_spec.rb
> Do not try to make API calls if token is not set for rfml lookups

- lib/rainforest/cli/resources.rb
- spec/resources_spec.rb
> cli prints 100 client folders instead of 10

- rainforest.go
- runner.go
- runner_test.go
specs still need to be written
> added search by folder id

- README.md
> Document rm and csv upload

- README.md
- lib/rainforest/cli.rb
- lib/rainforest/cli/http_client.rb
- lib/rainforest/cli/junit_outputter.rb
- lib/rainforest/cli/options.rb
- lib/rainforest/cli/reporter.rb
- lib/rainforest/cli/runner.rb
- rainforest-cli.gemspec
- spec/fixtures/failed_test_response.json
- spec/fixtures/runs_response.json
- spec/fixtures/tests_response.json
- spec/http_client_spec.rb
- spec/junit_outputter_spec.rb
- spec/options_spec.rb
- spec/reporter_spec.rb
> Junit Output (fix merge conflicts)

- lib/rainforest_cli/deleter.rb
- lib/rainforest_cli/exporter.rb
- lib/rainforest_cli/http_client.rb
- lib/rainforest_cli/options.rb
- lib/rainforest_cli/remote_tests.rb
- lib/rainforest_cli/test_files.rb
- lib/rainforest_cli/uploader.rb
- lib/rainforest_cli/validator.rb
- spec/rainforest_cli/exporter_spec.rb
- spec/rainforest_cli/options_spec.rb
- spec/rainforest_cli/remote_tests_spec.rb
- spec/rainforest_cli/validator_spec.rb
> Filter test downloads

- README.md
- lib/rainforest_cli/options.rb
- lib/rainforest_cli/test_files.rb
- spec/multiple-rainforest-examples/example_test.rfml
- spec/multiple-rainforest-examples/example_test_2.rfml
- spec/rainforest_cli/test_files_spec.rb
- spec/rainforest_cli/uploader_spec.rb
- spec/rainforest_cli/validator_spec.rb
> Filter uploads by tag, site id, or file path

- README.md
- lib/rainforest_cli.rb
- lib/rainforest_cli/csv_importer.rb
- lib/rainforest_cli/options.rb
- lib/rainforest_cli/runner.rb
- spec/rainforest_cli/csv_importer_spec.rb
> CSV Upload command

- lib/rainforest_cli.rb
- lib/rainforest_cli/commands.rb
- lib/rainforest_cli/options.rb
- spec/rainforest_cli/commands_spec.rb
- spec/rainforest_cli/options_spec.rb
- spec/rainforest_cli_spec.rb
> Add documentation for command in CLI help output

- lib/rainforest_cli/csv_importer.rb
- spec/rainforest_cli/csv_importer_spec.rb
> Use CSV batch upload endpoint for quicker, more reliable results

- lib/rainforest_cli/csv_importer.rb
- spec/rainforest_cli/csv_importer_spec.rb
Also retries upload if the request fails.
> Upload csv rows in chunks

- lib/rainforest_cli.rb
- lib/rainforest_cli/commands.rb
- spec/rainforest_cli_spec.rb
> ensures we register all currently supported commands

- lib/rainforest_cli/csv_importer.rb
- lib/rainforest_cli/deleter.rb
- lib/rainforest_cli/http_client.rb
- lib/rainforest_cli/reporter.rb
- lib/rainforest_cli/runner.rb
- spec/rainforest_cli/csv_importer_spec.rb
- spec/rainforest_cli/http_client_spec.rb
- spec/rainforest_cli/runner_spec.rb
- spec/rainforest_cli_spec.rb
- spec/spec_helper.rb
This retries not just on Timeouts, but also on non-200 status codes
> Add tolerance for server errors

- rainforest-cli.go
- rainforest-cli_test.go
- resources.go
- runner.go
- runner_test.go
@epaulet I moved around the fakecli and clicontext interface.
I'll merge it straight away, just leaving it here FYI.
> Testing framework qol

- rainforest/runner.go
- runner.go
> [Reviev] Add 'all' as possilbe Tests parameter

- .travis.yml
- circle.yml
- rainforest-cli.go
- rainforest/resources.go
- rainforest/tabularvars.go
- rainforest/tabularvars_test.go
- resources.go
- resources_test.go
- runner.go
- runner_test.go
- tabularvars.go
- tabularvars_test.go
> CSV upload

- rainforest-cli.go
- runner.go
@epaulet this is for https://github.com/rainforestapp/rainforest-cli/pull/214/files#diff-df6a65912ee01688949638589f5737f5R122
> [Review] change default mode to foreground

- circle.yml
- gittrigger.go
- gittrigger_test.go
- runner.go
> [Ready] git trigger in go

- circle.yml
- rainforest-cli.go
- runner.go
@epaulet this addresses: https://github.com/rainforestapp/rainforest-cli/pull/213#discussion_r90508050 and adds reattach/wait command.
> [Ready] Reattach option + timestamped error msgs

- rainforest/files.go
- rainforest/files_test.go
- rainforest/rainforest.go
This based off of the branch in #227
> [Review] Go file uploads

- .gitignore
- glide.lock
- glide.yaml
- rainforest-cli.go
- rainforest/rainforest.go
- rainforest/rfml.go
- rainforest/rfml_test.go
- rfml.go
- rfml_test.go
> [Review] RFML writer & "new" command

- rainforest/environments.go
- rainforest/environments_test.go
- runner.go
- runner_test.go
Just recently realized that this was missing
> [Review] Add custom-url behavior

- rainforest-cli.go
- rainforest-cli_test.go
This is a hack around the `urfave/cli` "issue" with global flags supplied as command parameters, not being recognized.
> add flags shuffle

- rainforest-cli.go
- rainforest/resources.go
- resources.go
- resources_test.go
Golang counterpart for https://github.com/rainforestapp/rainforest-cli/pull/247
> CLI v2: mobile v2 sites

- CHANGELOG.md
- lib/rainforest_cli/resources.rb
- lib/rainforest_cli/version.rb
- rainforest-cli.gemspec
- spec/rainforest_cli/resources_spec.rb
Sites now have categories (such as iOS, and Device Farm). These are minimal changes to support the addition of site categories.
> Mobile v2 sites command

- CHANGELOG.md
- lib/rainforest_cli/csv_importer.rb
- lib/rainforest_cli/version.rb
- spec/rainforest_cli/csv_importer_spec.rb
> RF-148 Make CSV upload not reliant on API order

- CHANGELOG.md
- lib/rainforest_cli/test_parser.rb
- lib/rainforest_cli/version.rb
fixes #244 
This duplicates the behavior of the dashboard.
> Default start URI to '/'

- CHANGELOG.md
- lib/rainforest_cli/constants.rb
- lib/rainforest_cli/version.rb
> Reduce threads to 4

- rainforest/rfml.go
- rainforest/rfml_test.go
Similar to the solution for the ruby version: #254
> Validate test title for v2

- rainforest-cli.go
- rainforest/resources.go
- rainforest/resources_test.go
- resources.go
- rfml.go
Sample output:
```
$ rainforest run-group 1 --token [REDACTED]
Details for Run Group #1:
Name: Zack Run group
Environment: Staging
Tester Crowd: default
Location: usa
Schedule: friday, thursday @ 19:00
```
> Fetch run group details

- README.md
- circle.yml
- rainforest-cli.go
- rainforest-cli_test.go
- rainforest/rainforest.go
- rainforest/rainforest_test.go
- rainforest/resources.go
- rainforest/rfml.go
- rainforest/rfml_test.go
- rainforest/runner.go
- rainforest/runner_test.go
- rainforest/tests.go
- rainforest/tests_test.go
- rfml.go
- rfml_test.go
- runner.go
- runner_test.go
This is the "dumb" way, but shouldn't require any changes on the
Rainforest end. It should be ready to go but I haven't tested
yet. @epaulet mind giving it a look?
> RF-2642 Run local tests only

- CHANGELOG.md
- rainforest-cli.go
- runner.go
Reverts rainforestapp/rainforest-cli#293
> Revert "RF-2852 Backoff if the API returns an error"

- CHANGELOG.md
- rainforest-cli.go
- runner.go
- runner_test.go
Reverts rainforestapp/rainforest-cli#301
> Revert "Revert "RF-2852 Backoff if the API returns an error""

- rainforest-cli.go
- rainforest/rainforest.go
> Propose lint and fix typos

- Dockerfile
Should fix https://circleci.com/gh/rainforestapp/beak/5023?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> RF-14781 Add TLS certs to the docker image

- rainforest/rfml.go
- rainforest/rfml_test.go
- rainforest/tests.go
- rainforest/tests_test.go
/reviewme @rainforestapp/backend @epaulet 
Did my best but honestly, serious copypasta. Please let me know if I biffed anything ❤️
> RF-14256 Set priority on RFML

- README.md
Thought it's worth mentioning here after https://github.com/rainforestapp/homebrew-public/pull/2/files
> Update README.md with homebrew-public release info

- README.md
- rainforest-cli.go
- runner.go
- runner_test.go
> RF-16284 add `automation_and_crowd` crowd option

- README.md
> Fix old reference to circle.yml

- CHANGELOG.md
- rainforest-cli.go
- rainforest/reporter.go
- reporter.go
- reporter_test.go
Add support for RFA failures that are reported differently
> RF-16455 Report RFA failures in Junit

- README.md
Get the CI build to run for #372
> update README.md to reference correct support documentation

- .github/workflows/codeql-analysis.yml
Turn on code scanning to see how it works.
> RF-18377 Enable GitHub's code scanning feature

- CHANGELOG.md
- README.md
With some extra cleanup to the README while I was remembering how releasing works.
> Release 2.16.0

- cloudbuild.yaml
Rewrite tagging for the docker image
> RF-18814 fix latest tag logic

- README.md
Making it have its own header will make it easier to link to.
> Update rerun documentation in README

- .circleci/config.yml
I'd like to release this to master and test if on `equinox` we'll get static executables
> RF-19498 Compile static executable

- .circleci/config.yml
- .gitignore
- .goreleaser.yml
- README.md
I've left in the Equinox CI jobs for now, but removed references to it in the README.
> [RF-21915] Switch to GoReleaser to build and release

- CHANGELOG.md
- rainforest-cli.go
- rainforest/runner.go
- rainforest/runner_test.go
- runner.go
Show a little more info in runs, and also better links to Rainforest's app when one starts.
https://rainforest.atlassian.net/browse/RF-22338
/reviewme @jbarber
> [RF-22338] Show a little more info in runs

- CHANGELOG.md
- rainforest-cli.go
- runner.go
> Fix for passed/failed being the wrong way around. 🤦

- README.md
As [talked about here](https://rainforest.slack.com/archives/C0286H6DR/p1632755370048700?thread_ts=1632705557.037400&cid=C0286H6DR), here are some draft docs for rollback. Anything else to add?
/reviewme @magni- @jbarber
> Add rollback docs to README

- .circleci/config.yml
- CHANGELOG.md
- rainforest-cli.go
> Remove requires for tags, as apparently they don't run

- README.md
@gep13 apparently we didn't have building of forks setup - and that may or may not work due to secrets in the build. I've pulled your commit in here.
closes #430 
/reviewme @rainforestapp/devs
> Gep13 patch 1 - update docs

- .circleci/config.yml
- .goreleaser.yml
- CHANGELOG.md
This changes binary names in releases back to ``rainforest`` from ``rainforest-cli``
/reviewme @jbarber @magni- @AJFunk
> RF 22544 - Fix the binary name

- LICENSE.txt
@smathieu - do you have any issues with this? I believe it could/should have been like this at the time, as you were working for us then?
> Update @smathieu --> @rainforestapp in the LICENSE

- README.md
> RF-22483 Add docs for windows / chocolatey

- Dockerfile
> Fix binary names in cli, also use same version of go to build

- CHANGELOG.md
- rainforest-cli.go
- rainforest-cli_test.go
The same as #373, but for the 🆕 GitHub Action
> [SEO-54] Add support for upcoming GitHub Action

- README.md
- runner.go
- Add links to CircleCI Orb and GitHub Action
- Tweak release documentation
- Fix typos
> Documentation tweaks

- CHANGELOG.md
- rainforest-cli.go
- runner.go
(internal: RF-24240)
DNM until 2022-09-15
> v3.0.0 - Drop support for deprecated `conflict` options

- CHANGELOG.md
- rainforest-cli.go
This version will include commands for working with branches:
- `branch new`
- `branch merge`
- `branch delete`
As well as add optional `--branch` param when:
- Uploading RFML
- Starting a run
> Bump version to v3.3.0

- .circleci/config.yml
See https://discuss.circleci.com/t/macos-resource-deprecation-update/46891
> RF-27778 Update macos executor

- .circleci/config.yml
Prerty sure this used to be present - so add it back to be included in the build process.
> Display git commit info for --version

- README.md
Just to make it easier for devs who haven't worked with Go before.
To see how it looks: https://github.com/rainforestapp/rainforest-cli/blob/readme_include_local_testing_instructions/README.md#testing-your-local-changes
> Include instructions for local testing in README
